### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by TheLonelyGuy1234** [MartinCrewGamer/MCGIncorporated-Service#1]
So if i send like a swear word the bot deletes it but doesn't DM me at all.
idk just attached a random pic cus i wont be able to send it without one :/
![down](https://user-images.githubusercontent.com/92183323/147236607-aa7327f5-d6b7-4161-bf6c-42e8303a5f54.png)

**Comment by MartinCrewGamer** [comment]
The bug will be fixed ASAP. We are apologies for inconvenience.
